name: Update Raya Prices from Excel

on:
  schedule:
    - cron: '0 0,12 * * *'
  workflow_dispatch:

permissions:      # السطرين دول هما اللي هيحلوا مشكلة 128
  contents: write 

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests beautifulsoup4 pandas openpyxl

      - name: Run Scraper
        run: python scraper.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "action@github.com"
          git add prices.json
          # السطر ده بيمنع الإيرور لو الأسعار متغيرتش
          git commit -m "Auto-update prices from RayaShop" || echo "No changes to commit"
          git push
